server:
    port: 8080

spring:
    application:
        name: api-gateway

    cloud:
        gateway:
            routes:
                - id: zone-service
                  uri: lb://zone-service
                  predicates:
                      - Path=/zones/**

                - id: sensor-service
                  uri: lb://sensor-service
                  predicates:
                      - Path=/sensors/**

                - id: crop-service
                  uri: lb://crop-service
                  predicates:
                      - Path=/crops/**

                - id: automation-service
                  uri: lb://automation-service
                  predicates:
                      - Path=/automation/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
